#### data preprocess
```{r}
# choose date and change the char to num/Date
data_proc <- function(data,date_range){
  dt <- data[4:nrow(data),1:11]
  colnames(dt) <- c("date","bl_mp","q1","gw_ahd","q2","ec_25","q3","ec","q4","wt","q5")
dt <- dt[-1,]
dt$date<-gsub("00:00:00","",as.character(dt$date))
dt$date <-  as.Date(dt$date, format = "%d/%m/%Y")
dt <- dt[dt$date > date_range[1] &dt$date < date_range[2], ]
dt[,2:11] <- lapply(dt[,2:11],as.numeric)
dt_use <- as.data.frame(cbind(dt$date,dt$bl_mp,dt$gw_ahd,dt$ec_25,dt$ec,dt$wt))
colnames(dt_use) <- c("date","bl_mp","gw_ahd","ec_25","ec","wt")
# na replaced by mean
dt_use[,2:6] <- as.data.frame(lapply(dt_use[,2:6], function(x) replace_na(x,mean(x, na.rm = TRUE))))
dt_use$date <- as.Date(dt_use$date,origin="1970-01-01")
return(dt_use)
}
```



#### min_max transform
```{r}
min_max <- function(data){
  return((data-min(data))/(max(data)-min(data)))}
```

#### transformed data
```{r}
trans_data <- function(data){
  dt_use_trans <- as.data.frame(lapply(data[,2:6],min_max))
  dt_use_trans$date <- data$date
  return(dt_use_trans)
}
```

#### get the processed data
GW036334.1.1 date:"2013-11-15" - "2019-03-28"
GW093067.1.1 date:"2015-02-18" - "2018-12-12" 
GW036976.1.2 date:"2013-11-14" - "2019-03-28" 
GW965569.1.2 date: "2013-09-24" - "2019-01-16"

```{r}
data334 <- data_proc(GW036334.1.1,c("2013-11-15", "2019-03-28"))
data334_trans <- trans_data(data334)

data067 <- data_proc(GW093067.1.1,c("2015-02-18", "2018-12-12"))
data067_trans <- trans_data(data067)

data976 <- data_proc(GW036976.1.2,c("2013-11-14", "2019-03-28"))
data976_trans <- trans_data(data976)

data569 <- data_proc(GW965569.1.2,c("2013-09-24", "2019-01-16"))
data569_trans <- trans_data(data569)

```

```{r}
write.csv(data334_trans,"/Users/yiyima/Desktop/DARE Semester 1/Final Project Info/data334_trans.csv")
write.csv(data067_trans,"/Users/yiyima/Desktop/DARE Semester 1/Final Project Info/data067_trans.csv")
write.csv(data976_trans,"/Users/yiyima/Desktop/DARE Semester 1/Final Project Info/data976_trans.csv")
write.csv(data569_trans,"/Users/yiyima/Desktop/DARE Semester 1/Final Project Info/data569_trans.csv")
```

